scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'persona-web'
    metrics_path: /api/v1/metrics
    scheme: http
    static_configs:
      - targets: ['localhost:8000']
