version: "3.9"

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: persona_web
    working_dir: /app/python
    command: ["python", "-m", "app.main"]
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - PORT=8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - ./python/app/logs:/app/python/app/logs

  worker:
    build:
      context: .
    container_name: persona_worker
    working_dir: /app/python
    command: [
      "celery",
      "-A", "app.celery.celery_app.celery_app",
      "worker",
      "--pool=threads",
      "--concurrency=10",
      "-l", "info"
    ]
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - ./python/app/logs:/app/python/app/logs